[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "glib",
  "gobject-introspection",
  "gdk-pixbuf",
  "pango",
  "cairo",
  "harfbuzz",
  "fontconfig",
  "freetype"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "python app/app.py"
