[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "cairo", "pango", "gdk-pixbuf", "glib", "libffi", "harfbuzz", "freetype", "fontconfig"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]
